### ISSUE TITLE
When to provide the installation script for centos？

### ISSUE THREAD

**Issue by lxglove** [voiceip/oreka#15]
When to provide the installation script for centos？

**Comment by kingster** [comment]
We mostly use Debian based releases (debian9/ubuntu16) in our production servers. Even though the original project did support rpm based releases, I am not well aware of how to build rpm packages.  

Here are our debian packaging scripts  [make-deb](https://github.com/voiceip/oreka-build/blob/master/distribution/make-orkaudio-deb.sh)

A quick search showed that [deb to rpm conversion](https://www.maketecheasier.com/convert-deb-files-rpm/) is possible. Do try that out and check if that works. 

Otherwise, it will need native packaging to rpm, probably you might help with rpm creation steps?

**Comment by kingster** [comment]
People have been successfully using docker based orkaudio on centos, ref #33 

Given that it has been confirmed to run successfully on centos, I am closing this ticket. Please reopen if you can't use docker based builds and need native rpm installers.
