### ISSUE TITLE
Orktrack init connection:false success:false

### ISSUE THREAD

**Issue by adityapranavbhuvanapalli** [voiceip/oreka#60]
I followed the procedure for setting up the docker image.
Platform: RHEL 8 
The oreka database tables were created, so I presume the .war files setup was correct.
In the config.xml file, I made the required changes
`<Devices>eno2</Devices>`
When I run the docker container it gives me this error
`2021-09-14 05:50:08,012 ERROR orkclient:36 - apr_socket_connect connect failed errno:Connection refused
2021-09-14 05:50:08,012  WARN reporting:320 - [localhost:8080/orktrack] init connection:false success:false`

The interface eno2 is not shown in the available pcap devices
Instead it is showing eth0

`2021-09-14 05:50:07,993  INFO packet:1515 - Available pcap devices:
2021-09-14 05:50:07,993  INFO packet:1522 - * eth0 - 
2021-09-14 05:50:07,993  INFO packet:1522 - * any - Pseudo-device that captures on all interfaces
2021-09-14 05:50:08,009  INFO packet:1522 - * lo - 
2021-09-14 05:50:08,009  INFO packet:1522 - * nflog - Linux netfilter log (NFLOG) interface
2021-09-14 05:50:08,009  INFO packet:1522 - * nfqueue - Linux netfilter queue (NFQUEUE) interface
2021-09-14 05:50:08,009  INFO packet:1522 - * usbmon1 - USB bus number 1
2021-09-14 05:50:08,009  INFO packet:1522 - * usbmon2 - USB bus number 2
2021-09-14 05:50:08,009  INFO packet:1522 - * usbmon3 - USB bus number 3
`
if I ran ifconfig, I can see that the interface name is eno2

Is there any particular reason that this occurs?
And how do I rectify this?

**Comment by kingster** [comment]
>   The interface eno2 is not shown in the available pcap devices
> Instead it is showing eth0

When docker runs in `host networking mode (--net=host)` docker would bind the `eth0` of the container to the physical adapter on your host and this is the expected behaviour. You will not see the same name as your physical adapter.  Now there are two possible situations

1.  If `eno2` is your primary interface on your host, you can change the `config.xml` to use `eth0` instead as that is same as the primary physical adapter. 
2. `eno2` is not the primary interface, but a second nic on your host. In that case you need to mount that to the docker instance using [macvlan](https://docs.docker.com/network/macvlan/).

> 2021-09-14 05:50:08,012 ERROR orkclient:36 - apr_socket_connect connect failed errno:Connection refused 2021-09-14 05:50:08,012 WARN reporting:320 - [localhost:8080/orktrack] init connection:false success:false

This would happen as you might have configured the tracker hostname as `localhost` in your `config.xml` and it is not accessible from within the docker instance. When running inside docker it would mean the docker host. Try using the actual IP address of your tomcat host.

**Comment by adityapranavbhuvanapalli** [comment]
Thanks it worked
